**Instructions to Follow (Failing to follow these will result mark penalties).**


1.   You can **NOT** use any built-in function except len()
2.   You can use the **shape** tuple of numpy arrays
2.   You can **NOT** use any other python collections (e.g: tuple, dictionaries etc.) except array.
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.zeros((10), dtype = int) #Initializing an array length 10 with values 0

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.







In [3]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [4]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))


#Zigzag Walk

In [8]:
def walk_zigzag(floor):
  #To Do
  pass
  row,col = floor.shape
  #print(row,col)
  for i in range(col):
    if i % 2 ==0:
      for j in range(0,row,2):
        print(floor[j][i],end=" ")
      print()
    else:
      if row % 2 != 0:
        for j in range(row-2,-1,-2):
          print(floor[j][i],end=" ")
        print()
      elif row % 2 == 0:
        for j  in range(row-1,-1,-2):
          print(floor[j][i],end=" ")
        print()

def print_matrix(matrix):
  for row in matrix:
    print("| " + " | ".join(row) + " |")


floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
print('################')
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

| 3 | 8 | 4 | 6 | 1 |
| 7 | 2 | 1 | 9 | 3 |
| 9 | 0 | 7 | 5 | 8 |
| 2 | 1 | 3 | 4 | 0 |
| 1 | 4 | 2 | 8 | 6 |
Walking Sequence:
3 9 1 
1 2 
4 7 2 
4 9 
1 8 6 
################
| 3 | 8 | 4 | 6 | 1 |
| 7 | 2 | 1 | 9 | 3 |
| 9 | 0 | 7 | 5 | 8 |
| 2 | 1 | 3 | 4 | 0 |
Walking Sequence:
3 9 
1 2 
4 7 
4 9 
1 8 


#Wall Up Trost District

In [14]:
def create_fence(district, depth):
    district_row, district_col = district.shape
    #TODO

    district_row += (2*depth)
    district_col += (2*depth)
    narr = np.zeros((district_row,district_col))


    for i in range(district_row):
      for j in range(district_col):
        narr[i][j] = 8

    a = 0
    for l in range(depth,district_row-depth):
      b = 0
      for k in range(depth,district_col-depth):

        narr[l][k] = district[a][b]
        b+=1
      a+=1

    return narr

def print_matrix(matrix):
  print(matrix)
depth = 1
district = np.array([[2,3,4], [3,4,6], [2,1,4]])
print_matrix(district)
ans = create_fence(district, depth)
print_matrix(ans)
#This will print
# |  8  |  8  |  8  |  8  |  8  |
# -------------------------------
# |  8  |  2  |  3  |  4  |  8  |
# -------------------------------
# |  8  |  3  |  4  |  6  |  8  |
# -------------------------------
# |  8  |  2  |  1  |  4  |  8  |
# -------------------------------
# |  8  |  8  |  8  |  8  |  8  |
# -------------------------------
print('################')
depth = 2
district = np.array([
                 [2,3,4,1],
                 [3,4,6,5],
                 [2,1,4,7]
                ])
print_matrix(district)
ans = create_fence(district, depth)
print_matrix(ans)


[[2 3 4]
 [3 4 6]
 [2 1 4]]
[[8. 8. 8. 8. 8.]
 [8. 2. 3. 4. 8.]
 [8. 3. 4. 6. 8.]
 [8. 2. 1. 4. 8.]
 [8. 8. 8. 8. 8.]]
################
[[2 3 4 1]
 [3 4 6 5]
 [2 1 4 7]]
[[8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 2. 3. 4. 1. 8. 8.]
 [8. 8. 3. 4. 6. 5. 8. 8.]
 [8. 8. 2. 1. 4. 7. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8.]]


#Crows vs Cats

In [15]:
def strength_difference(clubroom):
  strength_diff = np.zeros(100, dtype = int)
  #To Do
  row, col= clubroom.shape
  count= ((row*col)-row)//2
  strength_diff = np.zeros(count, dtype = int)

  k=0

  for i in range(0,row):
    for j in range (i+1,col):
      strength_diff[k]= (clubroom[i][j]) - (clubroom[j][i])
      j=i+1
      k+=1
    i+=1

  return strength_diff

clubroom = np.array([
[1,  2,  9,  7],
[4,  5,  1,  8],
[3,  6,  2,  7],
[2,  8,  6,  3]
])
print_matrix(clubroom)
returned_value = strength_difference(clubroom)
print('Strength Difference Array is : ', returned_value)
unittest.output_test(returned_value, np.array([-2, 6, 5, -5, 0, 1]))

[[1 2 9 7]
 [4 5 1 8]
 [3 6 2 7]
 [2 8 6 3]]
Strength Difference Array is :  [-2  6  5 -5  0  1]
Accepted


#ATM's Triangle

In [16]:
import numpy as np
def atm_triangle(n):
  arr = np.array([[None]*n]*n)
  r, c = arr.shape
  i = 0
  while i < r:
    j = 0
    while j <= i:
      if j==0 or j==i:
        arr[i][j] = i+1
      else:
        sum = 0
        counter = 0
        while counter <= j:
          sum += arr[i-1][counter]
          counter += 1
        arr[i][j] = sum
      j += 1
    i += 1
  return arr

def print_without_none(matrix):
  r, c = matrix.shape
  i = 0
  while i < r:
    j = 0
    while j < c:
      if matrix[i][j] != None:
        print(matrix[i][j], end = " ")
        j += 1
      else:
        break
    i += 1
    print()

n = 5
returned_value = atm_triangle(n)
print_without_none(returned_value)
#This should print
# 1
# 2  2
# 3  4  3
# 4  7  10  4
# 5  11 21  25  5

1 
2 2 
3 4 3 
4 7 10 4 
5 11 21 25 5 


#Trace The BOT

In [17]:
def moving_around(cmds):
  grid = np.full((7, 7), '.')

  #To Do
  row, col = grid.shape

  i,j=3,3
  grid[i][j] = "-"
  for k in range(len(cmds)):
    if cmds[k] == 1:
      i -= 2
      j -= 3
      if i>=0 and j>=0 and i<row and j<col:
        grid[i][j] = "*"
      else:
        i+=2
        j+=3
        grid[i][j] = "/"

    elif cmds[k] == 2:
      i -= 2
      j -=1
      if i>=0 and j>=0 and i<row and j<col:
        grid[i][j] = "*"
      else:
        i+=2
        j+=1
        grid[i][j] = "/"

    elif cmds[k] == 3:
      i-=3
      j-=2
      if i>=0 and j>=0 and i<row and j<col:
        grid[i][j] = "*"
      else:
        i+=3
        j+=2
        grid[i][j] = "/"

    elif cmds[k] == 4:
      i-=1
      j-=2
      if i>=0 and j>=0 and i<row and j<col:
        grid[i][j] = "*"
      else:
        i+=1
        j+=2
        grid[i][j] = "/"

    elif cmds[k] == 5:
      i-=2
      j+=1
      if i>=0 and j>=0 and i<row and j<col:
        grid[i][j] = "*"
      else:
        grid[i][j] = "/"

    elif cmds[k] == 6:
      i-=2
      j+=3
      if i>=0 and j>=0 and i<row and j<col:
        grid[i][j] = "*"
      else:
        i+=2
        j-=3
        grid[i][j] = "/"

    elif cmds[k] == 7:
      i-=3
      j+=2
      if i>=0 and j>=0 and i<row and j<col:
        grid[i][j] = "*"
      else:
        i+=3
        j-=2
        grid[i][j] = "/"

    elif cmds[k] == 8:
      i-=1
      j+=2
      if i>=0 and j>=0 and i<row and j<col:
        grid[i][j] = "*"

      else:
        i+=1
        j-=2
        grid[i][j] = "/"

    elif cmds[k] == 9:
      i+=2
      j-=3
      if i>=0 and j>=0 and i<row and j<col:
        grid[i][j] = "*"
      else:
        i-=2
        j+=3
        grid[i][j] = "/"

    elif cmds[k] == 10:
      i+=2
      j-=1
      if i>=0 and j>=0 and i<row and j<col:
        grid[i][j] = "*"
      else:
        i-=2
        j+=1
        grid[i][j] = "/"

    elif cmds[k] == 11:
      i+=1
      j-=2
      if i>=0 and j>=0 and i<row and j<col:
        grid[i][j] = "*"
      else:
        i-=1
        j+=2
        grid[i][j] = "/"

    elif cmds[k] == 12:
      i+=3
      j-=2
      if i>=0 and j>=0 and i<row and j<col:
        grid[i][j] = "*"
      else:
        i-=3
        j+=2
        grid[i][j] = "/"

  return grid


def print_matrix(matrix):
  for row in matrix:
    print("| " + " | ".join(row) + " |")
    print("-" * (7 * 4 + 1))



cmds = np.array([5,11,2,9])
result = moving_around(cmds)
print_matrix(result)
#This should print
# -------------------------------------------
# |  .  |  /  |  .  |  .  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  .  |  *  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  *  |  .  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  -  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  .  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  .  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  .  |  .  |  .  |  .  |
# -------------------------------------------

| . | / | . | . | . | . | . |
-----------------------------
| . | . | . | . | * | . | . |
-----------------------------
| . | . | * | . | . | . | . |
-----------------------------
| . | . | . | - | . | . | . |
-----------------------------
| . | . | . | . | . | . | . |
-----------------------------
| . | . | . | . | . | . | . |
-----------------------------
| . | . | . | . | . | . | . |
-----------------------------
