#### Part 1: 
#### Task 1: No issues apart from the usage of negative indexing once in every rotation iteration.  
#### Task 2: No issues. 
#### Task 3: No issues. 
#### Task 4: No issues apart from the usage of the numpy sum function. 
#### Task 5: Almost correct logic, outputs don't match. Usage of numpy functions are not allowed. 
#### Bonus Task: Not attempted. 
#### Part 2 Task: No issues. 

In [1]:
import numpy as np

**Instructions to Follow (Failing to follow these will result mark deductions).**


1.   You can not use any built-in function except len()
2.   You can not use any other python collections except array (e.g: tuptle, dictionaries etc.).
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.array([None] * 10) #Initializing an array length 10 with values None.

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.






In [1]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


You will see the status Accepted after completion if your code is correct.

If your function is wrong you will see wrong[correction percentage]

Do not change the driver code statements. You can only change the input values to test your code.

In [7]:
# Test 01: Play Right

def playRight(sequence, beats):

    # TO DO

 temp = 0

sequence = np.array([10,20,30,40,50,60])
beats = np.array([1,0,0,1,0,1])

def playRight(sequence,beats):
  for i in range(len(beats)):
     if beats[i] == 1:
      New_ARR = sequence[len(sequence)-1]
      for k in range(len(sequence)-1,-1,-1):  #swap
        sequence[k]= sequence[ k - 1]
     sequence[0] = New_ARR

  return sequence

print(playRight(sequence,beats))

    #return none

print("///  Test 01: Play Right  ///")
sequence = np.array([10, 20, 30, 40, 50, 60])
beats = np.array([1, 0, 0, 1, 0, 1])
returned_value = playRight(sequence, beats)
print(f'Task 1: {returned_value}')  # This should print [40, 50, 60, 10, 20, 30]

[40 50 60 10 20 30]
///  Test 01: Play Right  ///
Task 1: [40 50 60 10 20 30]


In [5]:
# Test 02: Discard Cards

def discardCards(cards,number):
  # TO DO


    result = np.zeros(len(cards), dtype=int)
    index = 0

    for card in cards:
        if card != number:
            result[index] = card
            index += 1

    return result

print("///  Test 02: Discard Cards  ///")
cards = np.array([1, 2, 3, 2, 8, 2, 2, 5, 7])
returned_value = discardCards(cards, 2)
print(returned_value)


  #return none


print("///  Test 02: Discard Cards  ///")
cards = np.array([1,2,3,2,8,2,2,5,7])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1, 3, 8, 5, 7, 0, 0, 0, 0]
unittest.output_test(returned_value, np.array([1, 3, 8, 5, 7, 0, 0, 0, 0]))

///  Test 02: Discard Cards  ///
[1 3 8 5 7 0 0 0 0]
///  Test 02: Discard Cards  ///
Task 2: [1 3 8 5 7 0 0 0 0]
Accepted


In [11]:
#Test 03: Merge Lineup
def mergeLineup(pokemon_1, pokemon_2):

  #result = [None]*len(pokemon_1) #this array stores the resulting array
  # TO DO

  new_line=np.zeros(len(pokemon_1),dtype=int)
  count=len(pokemon_1)-1
  for i in range(0,len(pokemon_1)):
      if pokemon_1[i]!=None and pokemon_2[count]!=None:
        new_line[i]=pokemon_1[i]+pokemon_2[count]
        count-=1
      else:
        if pokemon_1[i]==None and pokemon_2[count]!=None:
          new_line[i]=0+pokemon_2[count]
          count-=1
        elif pokemon_1[i]!=None and pokemon_2[count]==None:
          new_line[i]=pokemon_1[i]+0
          count-=1
        else:
          new_line[i]=0
          count-=1
  return new_line

pokemon_1=np.array([4, 5, -1, None, None])
pokemon_2=np.array([2, 27, 7, 12, None])
print(mergeLineup(pokemon_1, pokemon_2))







print("///  Test 03: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

[ 4 17  6 27  2]
///  Test 03: Merge Lineup  ///
Task 3: [12  3 28 -8  5]
Accepted
Task 3: [ 4 17  6 27  2]
Accepted


In [13]:
# Test 04: Balance your Salami
def balanceSalami(salami):

  # TO DO

  total_sum = np.sum(salami)
  left_sum = 0

  for i in range(len(salami) - 1):
          left_sum += salami[i]
          if left_sum == total_sum - left_sum:
              return True

  return False





  #return None

print("///  Test 04: Balance Your Salami  ///")
salami = np.array([1, 1, 1, 2, 1])
returned_value = balanceSalami(salami)
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = [2, 1, 1, 2, 1]
returned_value = np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

salami = [10, 3, 1, 2, 10]
returned_value =  np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

///  Test 04: Balance Your Salami  ///
Task 4: True
Accepted
Task 4: False
Accepted
Task 4: True
Accepted


In [5]:
# Test 05: Protecc Salami
def protectSalami(salami):
  # TO DO

  counts = np.bincount(salami)
  repeated_notes = np.where(counts >= 2)[0]
  if len(repeated_notes) >= 2:
        return True

  return False

  #return None



print("///  Test 05: Protecc Salami  ///")
salami = np.array([4,5,6,6,4,3,6,4])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print True
# unittest.output_test(returned_value, True)

salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print False
# unittest.output_test(returned_value, False)

///  Test 05: Protecc Salami  ///
[0 0 0 1 3 1 3]
[4 6]
Task 5: True
[0 0 0 2 3 0 4 1 1]
[3 4 6]
Task 5: True


In [15]:
#part 2

given_array=[10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4]
def standard_deviation(given_array):
  sum =0
  mean=0
  for i in given_array:
    sum +=i
    mean=sum /len(given_array)
  print(mean)
  sum2=0
  for x in given_array:
    sum2=sum2+((x-mean)*(x-mean))
  var=sum2/(len(given_array)-1)
  std=var**.5
  print(std)
  coin=0
  for j in given_array:
    if (j-mean)<=std*-1.5 or (j-mean)>=std*1.5:
      coin+=1
  new_array=[None]*coin
  j=0
  for m in given_array:
    if (m-mean)<=std*-1.5 or (m-mean)>=std*1.5:
      new_array[j]=m
      j+=1
  print(new_array)
standard_deviation([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])

10.181818181818182
7.960127911260996
[25, -5]


BONUS TASK (Ungraded)

In [ ]:
# Test 06: Odd Even Wave
def waveYourFlag(arr):
  # TO DO
  return None

print("///  Test 06: Odd Even Wave  ///")
arr = np.array([2,12,3,8,1,5])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [2,3,12,1,8,5]
unittest.output_test(returned_value, np.array([2,3,12,1,8,5]))

arr = np.array([45,23,78,84,41])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [45,78,23,84,41]
unittest.output_test(returned_value, np.array([45,78,23,84,41]))