#### Part 1: 
#### Task 1: No issues. 
#### Task 2: No issues. 
#### Task 3: No issues. 
#### Task 4: No issues. 
#### Task 5: No issues. 
#### Bonus Task: Almost correct. Can't handle the presence of duplicates. 
#### Part 2 Task: No issues. 

In [1]:
import numpy as np

**Instructions to Follow (Failing to follow these will result mark deductions).**


1.   You can not use any built-in function except len()
2.   You can not use any other python collections except array (e.g: tuptle, dictionaries etc.).
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.array([None] * 10) #Initializing an array length 10 with values None.

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.






In [3]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


You will see the status Accepted after completion if your code is correct.

If your function is wrong you will see wrong[correction percentage]

Do not change the driver code statements. You can only change the input values to test your code.

In [10]:
# Test 01: Play Right
def playRight(sequence, beats):
  for b in beats:
    if b == 1:
      temp = sequence[len(sequence)-1]
      for i in range(len(sequence)-1,0,-1):
        sequence[i] = sequence[i-1]
      sequence[0] = temp


  return sequence

print("///  Test 01: Play Right  ///")
sequence = np.array([10, 20, 30, 40, 50, 60])
beats = np.array([1, 0, 0, 1, 0, 1])
returned_value = playRight(sequence, beats)
print(f'Task 1: {returned_value}')  # This should print [40, 50, 60, 10, 20, 30]

///  Test 01: Play Right  ///
Task 1: [40 50 60 10 20 30]


In [5]:
# Test 02: Discard Cards
def discardCards(cards,number):
  i = 0
  while i < len(cards):
    if cards[i]==number:
      for j in range(i,len(cards)-1):
        cards[j]=cards[j+1]
        cards[j+1]=0
        print(cards)
      print()
      i -=1
    i+=1

  return cards


print("///  Test 02: Discard Cards  ///")
cards = np.array([1,2,3,2,8,2,2,5,7])
returned_value = discardCards(cards, 2)
print(f'Task 2: {returned_value}') # This should print [1, 3, 8, 5, 7, 0, 0, 0, 0]
# unittest.output_test(returned_value, np.array([1, 3, 8, 5, 7, 0, 0, 0, 0]))

///  Test 02: Discard Cards  ///
[1 3 0 2 8 2 2 5 7]
[1 3 2 0 8 2 2 5 7]
[1 3 2 8 0 2 2 5 7]
[1 3 2 8 2 0 2 5 7]
[1 3 2 8 2 2 0 5 7]
[1 3 2 8 2 2 5 0 7]
[1 3 2 8 2 2 5 7 0]

[1 3 8 0 2 2 5 7 0]
[1 3 8 2 0 2 5 7 0]
[1 3 8 2 2 0 5 7 0]
[1 3 8 2 2 5 0 7 0]
[1 3 8 2 2 5 7 0 0]
[1 3 8 2 2 5 7 0 0]

[1 3 8 2 0 5 7 0 0]
[1 3 8 2 5 0 7 0 0]
[1 3 8 2 5 7 0 0 0]
[1 3 8 2 5 7 0 0 0]
[1 3 8 2 5 7 0 0 0]

[1 3 8 5 0 7 0 0 0]
[1 3 8 5 7 0 0 0 0]
[1 3 8 5 7 0 0 0 0]
[1 3 8 5 7 0 0 0 0]
[1 3 8 5 7 0 0 0 0]

Task 2: [1 3 8 5 7 0 0 0 0]


In [8]:
#Test 03: Merge Lineup
def mergeLineup(pokemon_1, pokemon_2):
  result = np.zeros(len(pokemon_1),dtype = int)
  for i in range(len(pokemon_1)):
    if pokemon_1[i] == None:
      pokemon_1[i] = 0
    else:
      continue
  for i in range(len(pokemon_2)):
    if pokemon_2[i] == None:
      pokemon_2[i] = 0
    else:
      continue
  j = len(pokemon_2)-1
  for i in range(len(result)):
    result[i] = pokemon_1[i] + pokemon_2[j]
    j = j-1
  return result


print("///  Test 03: Merge Lineup  ///")
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None] )
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [12, 3, 28, -8, 5]
unittest.output_test(returned_value, np.array([12, 3, 28, -8, 5]))

pokemon_1 = np.array([4, 5, -1, None, None])
pokemon_2 = np.array([2, 27, 7, 12, None])
returned_value =mergeLineup(pokemon_1, pokemon_2)
print(f'Task 3: {returned_value}') # This should print [4,17,6,27,2]
unittest.output_test(returned_value, np.array([4,17,6,27,2]))

///  Test 03: Merge Lineup  ///
Task 3: [12  3 28 -8  5]
Accepted
Task 3: [ 4 17  6 27  2]
Accepted


In [ ]:
# Test 04: Balance your Salami
def balanceSalami(salami):
  total_salami = 0
  for s in salami:
    total_salami += s
  flag = False
  my_salami = 0
  j = 0
  while(j < len(salami)):
    my_salami += salami[j]
    if my_salami == (total_salami - my_salami):
      flag = True
      break
    j = j + 1

  return flag

print("///  Test 04: Balance Your Salami  ///")
salami = np.array([1, 1, 1, 2, 1])
returned_value = balanceSalami(salami)
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

salami = [2, 1, 1, 2, 1]
returned_value = np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print False
unittest.output_test(returned_value, False)

salami = [10, 3, 1, 2, 10]
returned_value =  np.array(balanceSalami(salami))
print(f'Task 4: {returned_value}') # This should print True
unittest.output_test(returned_value, True)

///  Test 04: Balance Your Salami  ///
Task 4: True
Accepted
Task 4: False
Accepted
Task 4: True
Accepted


In [11]:
# Test 05: Protecc Salami
def protectSalami(salami):
  new_arr = np.array([0]*len(salami))
  track = 0
  counter_arr = np.array([1]*len(salami))
  for i in salami :
      if i not in new_arr:
          new_arr[track] = i
          track += 1
      else:
          for j in range(len(new_arr)):
              if i == new_arr[j]:
                  counter_arr[j] += 1
              elif new_arr[j] == None:
                  break
  flag = False
  for i in range(len(counter_arr)):
      if counter_arr[i] > 1:
        for k in range(i+1,len(counter_arr)):
          if counter_arr[i] == counter_arr[k]:
            flag = True
            break
        break
  return flag

# print("///  Test 05: Protecc Salami  ///")
# salami = np.array([4,5,6,6,4,3,6,4])
# returned_value = protectSalami(salami)
# print(f'Task 5: {returned_value}') # This should print True
# unittest.output_test(returned_value, True)

salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
returned_value = protectSalami(salami)
print(f'Task 5: {returned_value}') # This should print False
# unittest.output_test(returned_value, False)

[2 1 1 1 1 1 1 1 1 1 1]
[2 2 1 1 1 1 1 1 1 1 1]
[2 3 1 1 1 1 1 1 1 1 1]
[2 3 2 1 1 1 1 1 1 1 1]
[2 3 3 1 1 1 1 1 1 1 1]
[2 3 4 1 1 1 1 1 1 1 1]
Task 5: False


BONUS TASK (Ungraded)

In [14]:
# Test 06: Odd Even Wave
def waveYourFlag(arr):
  m = len(arr)
  n_arr = np.zeros(len(arr),dtype=int)
  n_arr[0] = arr[0]
  for i in range(1,m):
    if n_arr[i-1] % 2 == 0:
      for j in arr:
        if j not in n_arr and j % 2 != 0:
          n_arr[i] = j
          break
        else:
          continue
    else:
      for j in arr:
        if j not in n_arr and j % 2 == 0:
          n_arr[i] = j
          break
        else:
          continue
  return n_arr


print("///  Test 06: Odd Even Wave  ///")
arr = np.array([2,2,13,12,3,8,1,5])
returned_value = waveYourFlag(arr)
print(f'Task 6: {returned_value}') # This should print [2,3,12,1,8,5]
# unittest.output_test(returned_value, np.array([2,3,12,1,8,5]))

# arr = np.array([45,23,78,84,41])
# returned_value = waveYourFlag(arr)
# print(f'Task 6: {returned_value}') # This should print [45,78,23,84,41]
# unittest.output_test(returned_value, np.array([45,78,23,84,41]))

///  Test 06: Odd Even Wave  ///
Task 6: [ 2 13 12  3  8  1  0  5]


In [16]:
#LAB01_PART02
def mean_calculator(arr):
  sum = 0
  for num in arr:
    sum += num
  mean = sum / len(arr)
  return mean

def st_deviation(arr):
  m = mean_calculator(arr)
  n = len(arr)
  sum = 0
  for i in range(len(arr)):
    sum += (arr[i] - m) ** 2
  dev = (sum / (n - 1)) ** 0.5
  return dev

def ranged_distance(arr):
  m = mean_calculator(arr)
  sd = st_deviation(arr)
  upper_bound = m + (1.5 * sd)
  lower_bound = m - (1.5 * sd)
  count = 0
  for i in arr:
    if i > upper_bound or i < lower_bound:
      count += 1
  n_arr = np.array([None]*count)
  j = 0
  for i in arr:
    if i > upper_bound or i < lower_bound:
      n_arr[j] = i
      j = j + 1
  if count > 0:
    return n_arr
  else:
    return None
# DRIVER CODE
test_arr = np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])
m = mean_calculator(test_arr)
print("The mean of the numbers is:",m)
sd = st_deviation(test_arr)
print("The standard deviation is:",round(sd,2))
a = ranged_distance(test_arr)
print("New array:",a)

The mean of the numbers is: 10.181818181818182
The standard deviation is: 7.96
New array: [25 -5]
